frr version 10.2
frr defaults traditional
hostname CORE1.SJO1
log syslog informational
!
interface lo
 ip address 1.0.0.1/32
 ip ospf area 0
!
interface eth1
 description to CORE2.SJO1
 ip address 1.255.0.1/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description to EDGE1.SJO1
 ip address 1.255.0.5/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth3
 description to EDGE2.SJO1
 ip address 1.255.0.9/30
 ip ospf area 0
 ip ospf network point-to-point
!
! Only static route in the network - blackhole aggregate so BGP can originate it
ip route 1.0.0.0/8 blackhole
!
router ospf
 ospf router-id 1.0.0.1
 passive-interface lo
!
router bgp 1
 bgp router-id 1.0.0.1
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 neighbor 1.0.0.2 remote-as 1
 neighbor 1.0.0.2 description CORE2.SJO1
 neighbor 1.0.0.2 update-source lo
 !
 neighbor 1.0.0.3 remote-as 1
 neighbor 1.0.0.3 description EDGE1.SJO1
 neighbor 1.0.0.3 update-source lo
 !
 neighbor 1.0.0.4 remote-as 1
 neighbor 1.0.0.4 description EDGE2.SJO1
 neighbor 1.0.0.4 update-source lo
 !
 address-family ipv4 unicast
  ! CORE1 is RR - EDGE routers are clients, CORE2 is a regular iBGP peer
  neighbor 1.0.0.2 activate
  neighbor 1.0.0.2 next-hop-self
  neighbor 1.0.0.3 activate
  neighbor 1.0.0.3 route-reflector-client
  neighbor 1.0.0.3 next-hop-self
  neighbor 1.0.0.4 activate
  neighbor 1.0.0.4 route-reflector-client
  neighbor 1.0.0.4 next-hop-self
  network 1.0.0.0/8
 exit-address-family
!
