frr version 10.2
frr defaults traditional
hostname EDGE1.SJO1
log syslog informational
!
interface lo
 ip address 1.0.0.3/32
 ip ospf area 0
!
interface eth1
 description to CORE1.SJO1
 ip address 1.255.0.6/30
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description to CORE2.SJO1
 ip address 1.255.0.14/30
 ip ospf area 0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 1.0.0.3
 passive-interface lo
!
router bgp 1
 bgp router-id 1.0.0.3
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 !
 ! Peer with both CORE RRs - provides redundancy if one CORE fails
 neighbor 1.0.0.1 remote-as 1
 neighbor 1.0.0.1 description CORE1.SJO1
 neighbor 1.0.0.1 update-source lo
 !
 neighbor 1.0.0.2 remote-as 1
 neighbor 1.0.0.2 description CORE2.SJO1
 neighbor 1.0.0.2 update-source lo
 !
 address-family ipv4 unicast
  neighbor 1.0.0.1 activate
  neighbor 1.0.0.2 activate
 exit-address-family
!
